version: "3.8"

services:
  bank-db:
    container_name: bank-db
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
