name: bank.be-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: bank
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Setup Go
        uses: actions/checkout@v2
        with:
          go-version: 1.23.2
        id: go

      - name: Checkout into Go Module
        uses: actions/checkout@v2

      - name: Download Go Dependencies
        run: go mod download

      - name: Install golang-migrate CLI
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.1/migrate.linux-amd64.tar.gz -o migrate.tar.gz
          tar xvz -f migrate.tar.gz
          sudo mv migrate /usr/bin/migrate
          which migrate

      - name: Migrate DB
        run: make dbmigrateup

      - name: Test
        run: make test