name: bank.be-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/checkout@v2
        with:
          go-version: 1.23.2
        id: go

      - name: Checkout into Go Module
        uses: actions/checkout@v2

      - name: Test
        run: make test
